galaxy_info:
  author: rdrgporto
  description: Install Elastic Agent

  license: Apache-2.0

  min_ansible_version: '2.1'

  platforms:
    - name: Ubuntu
      versions:
        - 'focal'

  galaxy_tags: []

dependencies: []
