galaxy_info:
  author: rdrgporto
  description: Install Packetbeat

  license: Apache-2.0

  min_ansible_version: '2.1'

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal

  galaxy_tags: []

dependencies: []
